# -*- coding: utf-8 -*-
"""S001_Coleta_Corpus_Framing_Israel_Palestina(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUkltDQSS_YcuRfh53nn9_7BQIhwPjt8

# Notebook 01 — Coleta do Corpus: Framing do Conflito Israel-Palestina na Imprensa

**Tema:** Como diferentes veículos de imprensa (americanos, do Oriente Médio e do Leste Asiático) enquadram (*framing*) o conflito Israel-Palestina.

Este notebook cobre a **primeira etapa** do projeto:

1. Definição dos grupos de veículos e configuração da coleta;
2. Coleta de metadados de artigos via **NewsAPI** (busca por palavra-chave **no título**, por domínio);
3. Extração do texto completo, detecção de idioma, tradução para inglês e salvamento — tudo em um
   único laço **com salvamento incremental**, para não perder progresso se a sessão do Colab cair;
4. Consolidação dos metadados e estatísticas básicas de coleta.

## 1. Instalando e importando as bibliotecas
"""

!pip install -q requests beautifulsoup4 pandas trafilatura langdetect deep-translator

from pathlib import Path
import hashlib
import json
import re
import time

import pandas as pd
import requests
import trafilatura
from langdetect import detect, DetectorFactory
from deep_translator import GoogleTranslator

DetectorFactory.seed = 42  # detecção de idioma determinística

print("Bibliotecas importadas.")

"""## 2. Salvamento dos arquivos no google drive e pasta raiz do corpus



"""

USE_DRIVE = True

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')
    raiz = Path("/content/drive/MyDrive/CorpusFramingIsraelPalestina")
else:
    raiz = Path("CorpusFramingIsraelPalestina")

print("Pasta raiz do corpus:", raiz.resolve())

"""## 3. Configuração da coleta

A chave da NewsAPI é pedida com `getpass`, dessa forma, é seguro passar pro repositório no github também

"""

from getpass import getpass
from datetime import datetime, timedelta

NEWS_API_KEY = getpass("Cole sua chave da NewsAPI: ")
NEWS_API_URL = "https://newsapi.org/v2/everything"

HEADERS = {
    "User-Agent": (
        "CorpusFramingIsraelPalestinaEducacional/1.0 "
        "(atividade academica; contato: seu-email@example.com)"
    )
}

PAUSA_ENTRE_REQUISICOES = 1
TIMEOUT = 20

# Janela de tempo (plano gratuito: até ~1 mês, com atraso de 24h para artigos recentes)
DATA_FIM    = (datetime.now() - timedelta(days=2)).strftime("%Y-%m-%d")
DATA_INICIO = (datetime.now() - timedelta(days=29)).strftime("%Y-%m-%d")

# Termo de busca — aplicado apenas ao TÍTULO do artigo (ver searchIn na busca, seção 5)
TERMOS_BUSCA = "Israel AND (Palestine OR Gaza OR Hamas)"

"""## 4. Grupos de veículos"""

GRUPOS_VEICULOS = {
    "eua": {
        "CNN": {"domain": "cnn.com", "idioma_original": "en"},
        "Fox News": {"domain": "foxnews.com", "idioma_original": "en"},
        "AP News": {"domain": "apnews.com", "idioma_original": "en"},
    },
    "brasil": {
        "UOL": {"domain": "uol.com.br", "idioma_original": "pt", "termos": 'Israel OR Palestina OR Gaza OR Hamas'},
        "Metrópoles": {"domain": "metropoles.com", "idioma_original": "pt", "termos": 'Israel OR Palestina OR Gaza OR Hamas'},
        "Terra": {"domain": "terra.com.br", "idioma_original": "pt", "termos": 'Israel OR Palestina OR Gaza OR Hamas'},
    },
    "oriente_medio": {
        "Al Jazeera": {"domain": "aljazeera.com", "idioma_original": "en"},
        "Anadolu Agency": {"domain": "aa.com.tr", "idioma_original": "en"},
        "Jerusalem Post": {"domain": "jpost.com", "idioma_original": "en"},
    },
    "asia_oriental": {
        "Channel News Asia": {"domain": "channelnewsasia.com", "idioma_original": "en"},
        "Straits Times": {"domain": "straitstimes.com", "idioma_original": "en"},
        "South China Morning Post": {"domain": "scmp.com", "idioma_original": "en"},
    },
}

for grupo, veiculos in GRUPOS_VEICULOS.items():
    print(grupo, "->", list(veiculos.keys()))

"""## 5. Criando a estrutura de pastas"""

pastas = ["dados_brutos", "dados_processados", "metadados", "logs", "resultados"]

for pasta in pastas:
    (raiz / pasta).mkdir(parents=True, exist_ok=True)

for grupo in GRUPOS_VEICULOS:
    (raiz / "dados_brutos" / grupo).mkdir(parents=True, exist_ok=True)

for caminho in sorted(raiz.rglob("*")):
    if caminho.is_dir():
        print(caminho)

"""## 6. Buscando artigos por veículo (metadados)



"""

def buscar_artigos(dominio, termos=TERMOS_BUSCA, tamanho_pagina=50):
    parametros = {
        "q": termos,
        "searchIn": "title,description",
        "domains": dominio,
        "from": DATA_INICIO,
        "to": DATA_FIM,
        "sortBy": "relevancy",
        "pageSize": tamanho_pagina,
        "apiKey": NEWS_API_KEY,
    }

    resposta = requests.get(NEWS_API_URL, params=parametros, headers=HEADERS, timeout=TIMEOUT)

    if resposta.status_code != 200:
        print(f"  -> detalhe do erro: {resposta.text}")

    resposta.raise_for_status()
    return resposta.json().get("articles", [])


registros = []

for grupo, veiculos in GRUPOS_VEICULOS.items():
    for nome_veiculo, info in veiculos.items():
        termos_veiculo = info.get("termos", TERMOS_BUSCA)
        try:
            artigos = buscar_artigos(info["domain"], termos=termos_veiculo)
        except Exception as erro:
            print(f"[ERRO] {nome_veiculo}: {erro}")
            continue

        print(f"{nome_veiculo} ({grupo}): {len(artigos)} artigos encontrados")

        for artigo in artigos:
            registros.append({
                "grupo": grupo,
                "veiculo": nome_veiculo,
                "dominio": info["domain"],
                "idioma_original_esperado": info["idioma_original"],
                "titulo": artigo.get("title"),
                "descricao": artigo.get("description"),
                "url": artigo.get("url"),
                "data_publicacao": artigo.get("publishedAt"),
            })

        time.sleep(PAUSA_ENTRE_REQUISICOES)

df_metadados = pd.DataFrame(registros).drop_duplicates(subset="url").reset_index(drop=True)
print("\nTotal de artigos coletados (metadados):", len(df_metadados))
df_metadados.head()

parametros = {
    "q": "Israel",
    "domains": "channelnewsasia.com",
    "from": DATA_INICIO,
    "to": DATA_FIM,
    "sortBy": "relevancy",
    "pageSize": 50,
    "apiKey": NEWS_API_KEY,
}
resposta = requests.get(NEWS_API_URL, params=parametros, headers=HEADERS, timeout=TIMEOUT)
artigos = resposta.json().get("articles", []) if resposta.status_code == 200 else []
print(f"Channel News Asia: {len(artigos)} artigos encontrados")

registros_cna = [{
    "grupo": "asia_oriental", "veiculo": "Channel News Asia", "dominio": "channelnewsasia.com",
    "idioma_original_esperado": "en",
    "titulo": a.get("title"), "descricao": a.get("description"),
    "url": a.get("url"), "data_publicacao": a.get("publishedAt"),
} for a in artigos]

df_cna = pd.DataFrame(registros_cna).drop_duplicates(subset="url")
df_metadados = pd.concat([df_metadados, df_cna]).drop_duplicates(subset="url").reset_index(drop=True)
print("\nTotal atualizado:", len(df_metadados))
print(df_metadados["grupo"].value_counts())

"""## 7. Extração, tradução e salvamento — com checkpoint incremental

Para cada artigo: extrai o texto completo (`trafilatura`), detecta o idioma, traduz para inglês
quando necessário, e **salva os arquivos em disco imediatamente**. A cada `INTERVALO_CHECKPOINT`
artigos, o progresso é gravado em `metadados/checkpoint.csv` — se a sessão cair, pula os artigos já processados.

"""

def gerar_id(url):
    return hashlib.sha256(url.encode("utf-8")).hexdigest()[:12]


def extrair_texto(url):
    try:
        html = trafilatura.fetch_url(url)
        if html is None:
            return None, "falha_download"
        texto = trafilatura.extract(html, include_comments=False, include_tables=False)
        if not texto or not texto.strip():
            return None, "texto_vazio"
        return texto.strip(), None
    except Exception as erro:
        return None, str(erro)


def detectar_idioma(texto):
    try:
        return detect(texto[:1000])
    except Exception:
        return "desconhecido"


def traduzir_para_ingles(texto, idioma_origem):
    TAMANHO_BLOCO = 4500
    blocos = [texto[i:i + TAMANHO_BLOCO] for i in range(0, len(texto), TAMANHO_BLOCO)]
    tradutor = GoogleTranslator(
        source=idioma_origem if idioma_origem != "desconhecido" else "auto", target="en"
    )
    traduzido = []
    for bloco in blocos:
        try:
            traduzido.append(tradutor.translate(bloco))
        except Exception as erro:
            traduzido.append(f"[ERRO DE TRADUCAO: {erro}]")
        time.sleep(0.3)
    return " ".join(traduzido)


INTERVALO_CHECKPOINT = 10
caminho_checkpoint = raiz / "metadados" / "checkpoint.csv"
caminho_erros = raiz / "logs" / "erros_processamento.json"

# retoma de onde parou, se já existir checkpoint de uma execução anterior
# retoma de onde parou, se já existir checkpoint válido de uma execução anterior
try:
    df_checkpoint = pd.read_csv(caminho_checkpoint)
    if df_checkpoint.empty:
        raise ValueError("checkpoint vazio")
    ids_processados = set(df_checkpoint["id"])
    resultados = df_checkpoint.to_dict("records")
    print(f"Checkpoint encontrado: {len(ids_processados)} artigos já processados. Retomando.")
except (FileNotFoundError, pd.errors.EmptyDataError, ValueError):
    ids_processados = set()
    resultados = []
    print("Nenhum checkpoint válido encontrado. Começando do zero.")

erros_processamento = []

for i, linha in df_metadados.iterrows():
    doc_id = gerar_id(linha["url"])
    if doc_id in ids_processados:
        continue

    texto_original, erro = extrair_texto(linha["url"])
    if texto_original is None:
        erros_processamento.append({"url": linha["url"], "veiculo": linha["veiculo"], "erro": erro})
        continue

    idioma = detectar_idioma(texto_original)
    if idioma == "en":
        texto_ingles = texto_original
        foi_traduzido = False
    else:
        texto_ingles = traduzir_para_ingles(texto_original, idioma)
        foi_traduzido = True

    (raiz / "dados_brutos" / linha["grupo"] / f"{doc_id}.txt").write_text(texto_original, encoding="utf-8")
    (raiz / "dados_processados" / f"{doc_id}.txt").write_text(texto_ingles, encoding="utf-8")

    resultados.append({
        "id": doc_id,
        "grupo": linha["grupo"],
        "veiculo": linha["veiculo"],
        "dominio": linha["dominio"],
        "data_publicacao": linha["data_publicacao"],
        "url": linha["url"],
        "titulo": linha["titulo"],
        "idioma_detectado": idioma,
        "foi_traduzido": foi_traduzido,
    })
    ids_processados.add(doc_id)

    if len(resultados) % INTERVALO_CHECKPOINT == 0:
        pd.DataFrame(resultados).to_csv(caminho_checkpoint, index=False, encoding="utf-8")
        print(f"  Checkpoint salvo: {len(resultados)} artigos processados até agora.")

    time.sleep(0.3)

# checkpoint final
pd.DataFrame(resultados).to_csv(caminho_checkpoint, index=False, encoding="utf-8")

with open(caminho_erros, "w", encoding="utf-8") as f:
    json.dump(erros_processamento, f, ensure_ascii=False, indent=2)

print("\nProcessamento concluído.")
print("Artigos processados com sucesso:", len(resultados))
print("Falhas (extração ou tradução):", len(erros_processamento))

"""## 8. Consolidando os metadados finais"""

df_meta_final = pd.DataFrame(resultados)

caminho_csv = raiz / "metadados" / "metadados_corpus.csv"
caminho_json = raiz / "metadados" / "metadados_corpus.json"

df_meta_final.to_csv(caminho_csv, index=False, encoding="utf-8")
df_meta_final.to_json(caminho_json, orient="records", force_ascii=False, indent=2)

print(caminho_csv)
print(caminho_json)
df_meta_final.head()

"""## 9. Estatísticas básicas da coleta"""

print("Total de artigos no corpus:", len(df_meta_final))
print()
print("Por grupo de veículo:")
print(df_meta_final["grupo"].value_counts())
print()
print("Por veículo:")
print(df_meta_final["veiculo"].value_counts())
print()
print("Traduzidos automaticamente:", df_meta_final["foi_traduzido"].sum())
print("Já em inglês:", (~df_meta_final["foi_traduzido"]).sum())



"""## 10. Exportando o corpus



"""

import shutil
from google.colab import files

caminho_zip = shutil.make_archive("CorpusFramingIsraelPalestina", "zip", raiz)
files.download(caminho_zip)