# -*- coding: utf-8 -*-
"""S005_Analise_Comparativa_Framing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ynPyxWCDAcb1-9YmZRZlzNUoNiCeMOi7

# Notebook 05 — Análise Comparativa de Enquadramento (Framing)

**Tema:** Como diferentes veículos de imprensa enquadram (*framing*) o conflito Israel-Palestina.

Ele parte do `corpus_pos.json` (Notebook 04) e das tabelas em
`resultados/` para produzir:

1. Nuvens de palavras por veículo (substantivos e adjetivos);
2. Comparação visual dos adjetivos associados a cada lado do conflito, por veículo;
3. Bigramas mais frequentes por veículo (colocações);
4. Uma tabela-resumo consolidada

## 1. Instalando e importando as bibliotecas
"""

!pip install -q wordcloud matplotlib pandas

from pathlib import Path
from collections import Counter

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

print("Bibliotecas importadas.")

"""## 2. Carregando os resultados do Notebook 04"""

USE_DRIVE = True

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')

CAMINHO_ESPERADO = Path("/content/drive/MyDrive/Corpus/CorpusFramingIsraelPalestina_resultsnotebook2/CorpusFramingIsraelPalestina")

if USE_DRIVE and not (CAMINHO_ESPERADO / "metadados" / "corpus_pos.json").exists():
    print("Caminho padrão não encontrado, procurando automaticamente no Drive...")
    encontrados = list(Path("/content/drive/MyDrive").rglob("corpus_pos.json"))
    if encontrados:
        raiz = encontrados[0].parent.parent
        print("Encontrado em:", raiz)
    else:
        raise FileNotFoundError("corpus_pos.json não encontrado em nenhum lugar do Drive.")
else:
    raiz = CAMINHO_ESPERADO if USE_DRIVE else Path("CorpusFramingIsraelPalestina_resultsnotebook2")

(raiz / "resultados").mkdir(parents=True, exist_ok=True)

df = pd.read_json(raiz / "metadados" / "corpus_pos.json")
print("Artigos carregados:", len(df))
print(df["veiculo"].value_counts())
df.head(3)

"""## 3. Nuvens de palavras por veículo

Uma nuvem para substantivos e outra para adjetivos, lado a lado, por veículo

"""

def gerar_nuvem(ax, contagem, titulo):
    if not contagem:
        ax.set_title(f"{titulo} (sem dados)")
        ax.axis("off")
        return
    nuvem = WordCloud(width=500, height=350, background_color="white", colormap="viridis")
    nuvem.generate_from_frequencies(contagem)
    ax.imshow(nuvem, interpolation="bilinear")
    ax.set_title(titulo)
    ax.axis("off")


veiculos = df["veiculo"].unique()
fig, eixos = plt.subplots(len(veiculos), 2, figsize=(12, 5 * len(veiculos)))
if len(veiculos) == 1:
    eixos = eixos.reshape(1, -1)

for i, veiculo in enumerate(veiculos):
    subset = df[df["veiculo"] == veiculo]
    contagem_subst = Counter(tok for lista in subset["substantivos"] for tok in lista)
    contagem_adj = Counter(tok for lista in subset["adjetivos"] for tok in lista)

    gerar_nuvem(eixos[i, 0], contagem_subst, f"{veiculo} — substantivos")
    gerar_nuvem(eixos[i, 1], contagem_adj, f"{veiculo} — adjetivos")

plt.tight_layout()
plt.savefig(raiz / "resultados" / "nuvens_palavras_por_veiculo.png", dpi=150, bbox_inches="tight")
plt.show()

"""## 4. Adjetivos associados a cada lado do conflito, por veículo

Gráfico de barras lado a lado: para cada veículo, os adjetivos mais usados em frases só sobre
Israel vs. só sobre Palestina/Gaza/Hamas (calculados no Notebook 04, seção 6). Essa é a comparação
central do projeto.

"""

TOP_N = 8

fig, eixos = plt.subplots(len(veiculos), 2, figsize=(12, 4 * len(veiculos)))
if len(veiculos) == 1:
    eixos = eixos.reshape(1, -1)

for i, veiculo in enumerate(veiculos):
    subset = df[df["veiculo"] == veiculo]

    contagem_israel = Counter(tok for lista in subset["adjetivos_israel"] for tok in lista)
    contagem_palestina = Counter(tok for lista in subset["adjetivos_palestina"] for tok in lista)

    top_israel = contagem_israel.most_common(TOP_N)
    top_palestina = contagem_palestina.most_common(TOP_N)

    if top_israel:
        palavras, frequencias = zip(*top_israel)
        eixos[i, 0].barh(palavras, frequencias, color="#4C72B0")
    eixos[i, 0].set_title(f"{veiculo} — adjetivos perto de ISRAEL")
    eixos[i, 0].invert_yaxis()

    if top_palestina:
        palavras, frequencias = zip(*top_palestina)
        eixos[i, 1].barh(palavras, frequencias, color="#DD8452")
    eixos[i, 1].set_title(f"{veiculo} — adjetivos perto de PALESTINA/GAZA/HAMAS")
    eixos[i, 1].invert_yaxis()

plt.tight_layout()
plt.savefig(raiz / "resultados" / "adjetivos_por_lado_e_veiculo.png", dpi=150, bbox_inches="tight")
plt.show()

"""## 5. Bigramas mais frequentes por veículo (colocações)

Pares de palavras consecutivas (usando os lemas sem stopwords) ajudam a identificar expressões
recorrentes que uma palavra isolada não mostra (ex: `"military operation"`, `"humanitarian crisis"`).

"""

def gerar_bigramas(lista_tokens):
    return list(zip(lista_tokens, lista_tokens[1:]))


TOP_N_BIGRAMAS = 10

for veiculo in veiculos:
    subset = df[df["veiculo"] == veiculo]
    todos_bigramas = Counter()
    for lista in subset["lemas_sem_stopwords"] if "lemas_sem_stopwords" in df.columns else []:
        todos_bigramas.update(gerar_bigramas(lista))

    print(f"\n=== {veiculo} — top {TOP_N_BIGRAMAS} bigramas ===")
    for (p1, p2), freq in todos_bigramas.most_common(TOP_N_BIGRAMAS):
        print(f"  {p1} {p2}  (freq={freq})")

"""## 6. Tabela-resumo consolidada

Uma linha por veículo: número de artigos, total de tokens, e os 3 adjetivos mais associados a cada
lado

"""

linhas_resumo = []

for veiculo in veiculos:
    subset = df[df["veiculo"] == veiculo]
    grupo = subset["grupo"].iloc[0]

    contagem_israel = Counter(tok for lista in subset["adjetivos_israel"] for tok in lista)
    contagem_palestina = Counter(tok for lista in subset["adjetivos_palestina"] for tok in lista)

    linhas_resumo.append({
        "veiculo": veiculo,
        "grupo": grupo,
        "num_artigos": len(subset),
        "total_tokens": subset["num_tokens"].sum() if "num_tokens" in subset.columns else None,
        "top3_adjetivos_israel": ", ".join(p for p, _ in contagem_israel.most_common(3)),
        "top3_adjetivos_palestina": ", ".join(p for p, _ in contagem_palestina.most_common(3)),
    })

df_resumo = pd.DataFrame(linhas_resumo)

caminho_resumo = raiz / "resultados" / "tabela_resumo_final.csv"
df_resumo.to_csv(caminho_resumo, index=False, encoding="utf-8")

print(caminho_resumo)
df_resumo

"""## Conclusão do projeto

Notebooks produzidos:

1. **Notebook 01** — Coleta do corpus (NewsAPI, extração de texto, tradução).
2. **Notebook 02** — Limpeza com regex.
3. **Notebook 03** — Normalização e tokenização (spaCy).
4. **Notebook 04** — Stopwords, lematização/stemming e POS tagging, com a extração de adjetivos por
   lado do conflito.
5. **Notebook 05** (este) — Nuvens de palavras, comparação visual, bigramas, tabela-resumo e
   interpretação final.

Arquivos de saída principais em `resultados/`: `nuvens_palavras_por_veiculo.png`,
`adjetivos_por_lado_e_veiculo.png`, `top_substantivos_por_veiculo.csv`,
`top_adjetivos_por_veiculo.csv`, `tabela_resumo_final.csv`.

"""