# -*- coding: utf-8 -*-
"""S002_Limpeza_Regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XjqkHJC-xrTSFEIA5RCteq1OTuTzSOs

# Notebook 02 — Limpeza do corpus com Regex
**Trabalho 1 de PLN — Corpus de framing Israel–Palestina**

Neste notebook carregamos o corpus construído no Notebook 01 e aplicamos uma **limpeza baseada em expressões regulares**:

1. remover *boilerplate* residual (chamadas do site, blocos de "Recommended Stories", créditos);
2. normalizar pontuação e aspas;
3. tratar erros de tradução (`[ERRO DE TRADUCAO: ...]`);
4. tratar datas.

Cada regra é aplicada separadamente e **contada**, para justificar a decisão no relatório técnico e mostrar o efeito da limpeza.

## 1. Carregamento do corpus
"""

from pathlib import Path
import re
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_colwidth", 80)

try:
    from google.colab import drive
    drive.mount("/content/drive")
    candidatos = list(Path("/content/drive/MyDrive").rglob("metadados_corpus.csv"))
    if candidatos:
        RAIZ = candidatos[0].parent.parent
        print("Corpus encontrado em:", RAIZ)
    else:
        RAIZ = Path("/content/drive/MyDrive/CorpusFramingIsraelPalestina")
        print("Nao encontrado automaticamente, usando caminho padrao:", RAIZ)
except ImportError:
    RAIZ = Path("CorpusFramingIsraelPalestina")

df_meta = pd.read_csv(RAIZ / "metadados" / "metadados_corpus.csv")

def carregar_texto(doc_id):
    caminho = RAIZ / "dados_processados" / f"{doc_id}.txt"
    return caminho.read_text(encoding="utf-8") if caminho.exists() else None

df_meta["texto"] = df_meta["id"].apply(carregar_texto)
df_meta = df_meta[df_meta["texto"].notna()].reset_index(drop=True)

print("Artigos carregados:", len(df_meta))
df_meta[["id", "grupo", "veiculo", "data_publicacao", "titulo"]].head()

"""## 2. Auditoria: o que há de "sujeira" no corpus?
Antes de limpar, medimos quantas vezes cada padrão aparece. Assim a limpeza é guiada pelos dados, e não por suposição.
"""

AUDITORIA = {
    "erro de tradução":        r"\[ERRO DE TRADUCAO[^\]]*\]",
    "bloco Recommended Stories": r"^Recommended Stories\s*$",
    "linha 'list of N items'": r"^list of \d+ items\s*$",
    "chamada CLICK HERE":      r"^\s*CLICK HERE\b.*$",
    "rótulo NewsFeed":         r"^\s*NewsFeed\s*$",
    "Published On ...":        r"^\s*Published On\b.*$",
    "crédito 'contributed'":   r"^.*\bcontributed to this report\.?\s*$",
    "aviso de opinião":        r"^The views expressed in this article\b.*$",
    "URLs":                    r"https?://\S+|www\.\S+",
    "@menções":                r"(?<!\w)@\w+",
    "aspas/apóstrofos curvos": r"[“”‘’]",
    "travessões/reticências":  r"[–—…]",
}
linhas = []
for nome, padrao in AUDITORIA.items():
    por_grupo = {}
    for grupo, sub in df_meta.groupby("grupo"):
        por_grupo[grupo] = sum(len(re.findall(padrao, t, flags=re.M)) for t in sub["texto"])
    linhas.append({"padrão": nome, **por_grupo, "total": sum(por_grupo.values())})

df_audit = pd.DataFrame(linhas)
df_audit

"""**O que a auditoria mostra:** a Al Jazeera traz blocos de *Recommended Stories* (manchetes de outras matérias coladas no meio do texto) e rótulos de página; a Fox News traz chamadas do tipo "CLICK HERE..." e créditos ao final. Esse material **não faz parte do argumento do artigo** e, se ficar, o modelo pode aprender o veículo em vez do enquadramento.

Um cuidado importante: as manchetes de *Recommended Stories* têm palavras fortes (por exemplo, "genocide") que **não foram escritas naquele artigo**. Mantê-las inflaria artificialmente a frequência desses termos.

### Conferência rápida por veículo
"""

for veiculo in df_meta["veiculo"].unique():
    exemplo = df_meta[df_meta["veiculo"] == veiculo].iloc[0]
    print(f"\n=== {veiculo} ===")
    print(exemplo["texto"][:400])

df_meta["tem_erro_traducao"] = df_meta["texto"].str.contains(r"\[ERRO DE TRADUCAO", regex=True)

n_antes = len(df_meta)
excluidos = df_meta[df_meta["tem_erro_traducao"]][["id", "veiculo", "grupo"]]

df_meta = df_meta[~df_meta["tem_erro_traducao"]].reset_index(drop=True)

print(f"Artigos excluídos por falha definitiva de tradução: {len(excluidos)}")
print(excluidos["veiculo"].value_counts())
print(f"\nCorpus final: {len(df_meta)} artigos (era {n_antes})")
print(df_meta["grupo"].value_counts())

!pip install -q langdetect deep-translator

"""## 3. Regras de limpeza (uma por vez, com contagem)"""

# Cada regra: (nome, regex, substituição, flags)
# A ORDEM importa: primeiro blocos e linhas inteiras, depois caracteres.
M = r"(?:Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May|June?|July?|Aug(?:ust|\.)?|Sept?(?:ember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)"

REGRAS = [
    # 1) Erros de tradução: remove a marcação e mantém o resto do texto
    ("erro de tradução", r"\[ERRO DE TRADUCAO[^\]]*\]", " ", re.I),

    # 2) Boilerplate (linhas inteiras)
    ("bloco Recommended Stories",
     r"^Recommended Stories\s*\n(?:list of \d+ items\s*\n)?(?:- list \d+ of \d+.*(?:\n|$))+", "", re.M),
    ("chamada CLICK HERE",   r"^\s*CLICK HERE\b.*$", "", re.M),
    ("rótulo NewsFeed",      r"^\s*NewsFeed\s*$", "", re.M),
    ("Published On",         r"^\s*Published On\b.*$", "", re.M),
    ("crédito 'contributed'", r"^.*\bcontributed to this report\.?\s*$", "", re.M),
    ("aviso de opinião",     r"^The views expressed in this article\b.*$", "", re.M),

    # 3) URLs e menções
    ("URLs",      r"https?://\S+|www\.\S+", " ", 0),
    ("@menções",  r"(?<!\w)@\w+", " ", 0),

    # 4) Pontuação e aspas
    ("aspas duplas curvas",   r"[“”„]", '"', 0),
    ("apóstrofos/aspas simples curvas", r"[‘’`´]", "'", 0),
    ("travessões",            r"[–—]", " - ", 0),
    ("reticências",           r"…", "...", 0),

    # 5) Datas
    # 'October 7' nomeia um evento (ataque de 7/10/2023), então é PROTEGIDO e padronizado
    ("proteger 'October 7'",  r"\bOct(?:ober|\.)?\s+7(?:,\s*2023)?\b", "OCTOBER7EVENT", 0),
    ("data dia-mês-ano",      r"\b\d{1,2}\s+" + M + r"\s+\d{4}\b", "<DATE>", 0),
    ("data mês dia, ano",     r"\b" + M + r"\s+\d{1,2}(?:,\s*\d{4})\b", "<DATE>", 0),
    ("data mês ano",          r"\b" + M + r"\s+\d{4}\b", "<DATE>", 0),
    ("data mês dia",          r"\b" + M + r"\s+\d{1,2}\b", "<DATE>", 0),
    ("data numérica",         r"\b\d{4}-\d{2}-\d{2}\b|\b\d{1,2}/\d{1,2}/\d{2,4}\b", "<DATE>", 0),
    ("restaurar 'October 7'", r"OCTOBER7EVENT", "October 7", 0),

    # 6) Espaços
    ("espaços repetidos",  r"[ \t\u00a0]+", " ", 0),
    ("espaço antes de quebra", r" *\n *", "\n", 0),
    ("linhas em branco",   r"\n{2,}", "\n", 0),
]

def limpar_texto(texto, contador=None):
    for nome, padrao, repl, flags in REGRAS:
        texto, n = re.subn(padrao, repl, texto, flags=flags)
        if contador is not None:
            contador[nome] = contador.get(nome, 0) + n
    return texto.strip()

# Teste rápido em um texto artificial
exemplo = """Israel kills 3 in Gaza — officials said on Sept. 3, 2026.
Recommended Stories
list of 2 items
- list 1 of 2Headline A
- list 2 of 2Headline B
“It’s a test [ERRO DE TRADUCAO: timeout]” said one. See https://example.com @user
Attack of Oct. 7 …
CLICK HERE TO DOWNLOAD THE APP"""
print(limpar_texto(exemplo))

"""### Por que essas decisões?
- **Blocos e linhas de boilerplate:** são elementos de interface do site, não conteúdo jornalístico.
- **Aspas e apóstrofos curvos → retos:** `don’t` e `don't` são a mesma palavra, mas seriam tokens diferentes.
- **Datas → `<DATE>`:** datas isoladas raramente carregam enquadramento, e transformá-las em um token único evita milhares de features raras.
- **Exceção: `October 7`:** é o nome de um evento e o próprio uso desse termo é relevante para *framing*. Por isso ele é preservado e padronizado.
- **Números como "73,470" foram mantidos** (contagens de mortos aparecem em vários textos e podem ser analisadas depois).

## 4. Aplicando a limpeza ao corpus
"""

contadores = {}
df_meta["texto_limpo"] = df_meta["texto"].apply(lambda t: limpar_texto(t, contadores))

df_meta["erro_traducao"] = df_meta["texto"].apply(lambda t: len(re.findall(r"\[ERRO DE TRADUCAO", t)))
df_meta["chars_antes"]   = df_meta["texto"].str.len()
df_meta["chars_depois"]  = df_meta["texto_limpo"].str.len()
df_meta["palavras_antes"]  = df_meta["texto"].str.split().str.len()
df_meta["palavras_depois"] = df_meta["texto_limpo"].str.split().str.len()

df_regras = (pd.Series(contadores, name="ocorrências")
               .rename_axis("regra").reset_index())
df_regras[df_regras["ocorrências"] > 0]

"""## 5. Impacto da limpeza"""

resumo = (df_meta.groupby("grupo")[["palavras_antes", "palavras_depois"]].sum())
resumo["removidas"] = resumo["palavras_antes"] - resumo["palavras_depois"]
resumo["% removido"] = (100 * resumo["removidas"] / resumo["palavras_antes"]).round(1)
resumo

# Visualização 1: palavras por documento, antes x depois
ordem = df_meta.sort_values(["grupo", "palavras_antes"]).reset_index(drop=True)
x = range(len(ordem))
fig, ax = plt.subplots(figsize=(11, 4))
ax.bar([i - 0.2 for i in x], ordem["palavras_antes"], width=0.4, label="antes")
ax.bar([i + 0.2 for i in x], ordem["palavras_depois"], width=0.4, label="depois")
ax.set_xticks(list(x))
ax.set_xticklabels(ordem["id"].str[:6] + "\n(" + ordem["grupo"].str[:3] + ")", fontsize=7)
ax.set_ylabel("nº de palavras")
ax.set_title("Palavras por documento antes e depois da limpeza")
ax.legend()
plt.tight_layout()
plt.show()

# Visualização 2: quais regras mais alteraram o corpus?
top = df_regras[df_regras["ocorrências"] > 0].sort_values("ocorrências")
fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(top["regra"], top["ocorrências"])
ax.set_xlabel("nº de substituições")
ax.set_title("Substituições por regra de limpeza")
plt.tight_layout()
plt.show()

"""## 6. Conferência manual (antes × depois)"""

def mostrar(doc_id, n=600):
    linha = df_meta[df_meta["id"].str.startswith(doc_id)].iloc[0]
    print("=== ANTES ===");  print(linha["texto"][:n])
    print("\n=== DEPOIS ==="); print(linha["texto_limpo"][:n])


mostrar(df_meta["id"].iloc[0], 900)

# Verificações automáticas: nada do boilerplate deveria sobrar
checagens = {
    "Recommended Stories": r"Recommended Stories",
    "list of N items":     r"list of \d+ items",
    "CLICK HERE":          r"CLICK HERE",
    "NewsFeed":            r"NewsFeed",
    "Published On":        r"Published On",
    "ERRO DE TRADUCAO":    r"ERRO DE TRADUCAO",
    "aspas curvas":        r"[“”‘’]",
    "URLs":                r"https?://",
}
for nome, p in checagens.items():
    sobrou = df_meta["texto_limpo"].str.contains(p, regex=True).sum()
    print(f"{nome:22s} documentos com resíduo: {sobrou}")

"""## 7. Documentos problemáticos
Textos muito curtos (por exemplo, páginas de vídeo da Al Jazeera, com poucas linhas de descrição) e textos com erro de tradução merecem decisão explícita, e essa decisão deve aparecer no relatório.
"""

LIMITE_PALAVRAS = 100
df_meta["texto_curto"] = df_meta["palavras_depois"] < LIMITE_PALAVRAS

problemas = df_meta[df_meta["texto_curto"] | (df_meta["erro_traducao"] > 0)]
problemas[["id", "grupo", "veiculo", "palavras_depois", "erro_traducao", "titulo"]]

"""## 8. Salvando o corpus limpo"""

SAIDA = RAIZ / "dados_limpos"
SAIDA.mkdir(exist_ok=True)

for _, linha in df_meta.iterrows():
    (SAIDA / f"{linha['id']}.txt").write_text(linha["texto_limpo"], encoding="utf-8")

colunas = ["id", "grupo", "veiculo", "data_publicacao", "url", "titulo",
           "idioma_detectado", "foi_traduzido", "erro_traducao",
           "palavras_antes", "palavras_depois", "texto_curto", "texto_limpo"]
df_meta[colunas].to_csv(RAIZ / "metadados" / "corpus_limpo.csv", index=False, encoding="utf-8")

print("Salvo em:", SAIDA)
print("CSV:", RAIZ / "metadados" / "corpus_limpo.csv")