# -*- coding: utf-8 -*-
"""S003_Normalizacao_Tokenizacao_Framing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCDtW_CrIpKr6PwdTy5rHNXuCeh7FmeX

# Notebook 03 — Normalização e Tokenização

**Tema:** Como diferentes veículos de imprensa enquadram (*framing*) o conflito Israel-Palestina.

Este notebook parte do `corpus_limpo.csv` gerado no Notebook 02 (coluna `texto_limpo`, já limpo por
regex) e produz:

1. Normalização adicional do texto (aspas/traços de tradução automática, espaços);
2. Tokenização com spaCy (`en_core_web_sm`) — o corpus inteiro já está em inglês, então não
   precisamos alternar entre modelos PT/EN como em aula (S006);
3. Duas versões dos tokens: com caixa original (`tokens`) e em minúsculas (`tokens_lower`);
4. Estatísticas básicas de tokens por veículo/grupo;
5. Exportação para os Notebooks 04/05.

> **Por que manter a caixa original também?** O Notebook 04 vai usar POS tagging para identificar
> como cada veículo descreve os lados do conflito. Entidades como *Israel*, *Gaza*, *Hamas*, nomes
> de pessoas etc. são mais fáceis de reconhecer com a caixa original preservada por isso geramos
> as duas versões em vez de só uma normalizada.

## 1. Instalando e importando as bibliotecas
"""

!pip install -q spacy nltk
!python -m spacy download en_core_web_sm -q

from pathlib import Path
import json
import re

import pandas as pd
import spacy

nlp = spacy.load("en_core_web_sm")
print("spaCy carregado:", nlp.meta["name"], nlp.meta["version"])

"""## 2. Carregando o corpus limpo (saída do Notebook 02)"""

USE_DRIVE = True

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')
    candidatos = list(Path("/content/drive/MyDrive").rglob("corpus_limpo.csv"))
    if candidatos:
        raiz = candidatos[0].parent.parent
        print("Corpus encontrado em:", raiz)
    else:
        raise FileNotFoundError("corpus_limpo.csv não encontrado em nenhum lugar do Drive.")
else:
    raiz = Path("CorpusFramingIsraelPalestina")

df = pd.read_csv(raiz / "metadados" / "corpus_limpo.csv")
df = df[df["texto_limpo"].notna()].reset_index(drop=True)

print("Artigos carregados:", len(df))
print(df["grupo"].value_counts())
df.head(3)

from pathlib import Path

encontrados = list(Path("/content/drive/MyDrive").rglob("corpus_limpo.csv"))

if not encontrados:
    print("Nenhum 'corpus_limpo.csv' encontrado no seu Drive.")
else:
    for caminho in encontrados:
        print(caminho)

"""## 3. Normalização adicional

Antes de tokenizar, resolvemos alguns resíduos comuns em texto traduzido automaticamente e extraído
da web: aspas curvas, travessões duplicados, espaços múltiplos, e qualquer marcador de erro de
tradução que possa ter sobrado (`[ERRO DE TRADUCAO: ...]`) do Notebook 01.

"""

def normalizar_texto(texto):
    texto = re.sub(r"\[ERRO DE TRADUCAO:.*?\]", " ", texto)          # remove marcadores de erro
    texto = texto.replace("\u201c", '"').replace("\u201d", '"')       # aspas curvas -> retas
    texto = texto.replace("\u2018", "'").replace("\u2019", "'")
    texto = re.sub(r"[\u2013\u2014]+", "-", texto)                    # travessões -> hífen simples
    texto = re.sub(r"\s+", " ", texto).strip()                        # espaços múltiplos
    return texto


df["texto_normalizado"] = df["texto_limpo"].apply(normalizar_texto)

exemplo = df.iloc[0]
print("ANTES: ", exemplo["texto_limpo"][:200])
print()
print("DEPOIS:", exemplo["texto_normalizado"][:200])

"""## 4. Tokenização com spaCy

Usamos `nlp.pipe` para processar todos os artigos de uma vez (mais rápido que rodar `nlp()` um por
um). Para cada artigo, guardamos:

- `tokens`: tokens alfabéticos, caixa original preservada (para entidades/POS no Notebook 04);
- `tokens_lower`: os mesmos tokens em minúsculas (para frequência/comparação bruta entre veículos);
- `num_tokens`: contagem de tokens, útil para checar artigos anormalmente curtos/longos.

Pontuação, números isolados e espaços são descartados

"""

def tokenizar(doc):
    tokens = [tok.text for tok in doc if tok.is_alpha]
    return tokens


textos = df["texto_normalizado"].tolist()
todos_tokens = []

for doc in nlp.pipe(textos, batch_size=32, disable=["parser", "ner"]):
    todos_tokens.append(tokenizar(doc))

df["tokens"] = todos_tokens
df["tokens_lower"] = df["tokens"].apply(lambda lista: [t.lower() for t in lista])
df["num_tokens"] = df["tokens"].apply(len)

df[["id", "veiculo", "grupo", "num_tokens"]].head(10)

"""## 5. Estatísticas de tokens por veículo e grupo"""

print("Tokens por veículo (média):")
print(df.groupby("veiculo")["num_tokens"].mean().round(1))
print()
print("Tokens por grupo (total e média):")
print(df.groupby("grupo")["num_tokens"].agg(["sum", "mean", "count"]).round(1))

import matplotlib.pyplot as plt

media_por_veiculo = df.groupby("veiculo")["num_tokens"].mean().sort_values()

plt.figure(figsize=(8, 4))
media_por_veiculo.plot(kind="barh")
plt.xlabel("Média de tokens por artigo")
plt.title("Tamanho médio dos artigos, por veículo")
plt.tight_layout()
plt.show()

"""## 7. Exportando para o Notebook 04



"""

caminho_json = raiz / "metadados" / "corpus_tokenizado.json"
caminho_csv = raiz / "metadados" / "corpus_tokenizado.csv"

df.to_json(caminho_json, orient="records", force_ascii=False, indent=2)

df_csv = df.copy()
df_csv["tokens"] = df_csv["tokens"].apply(lambda lista: " | ".join(lista))
df_csv["tokens_lower"] = df_csv["tokens_lower"].apply(lambda lista: " | ".join(lista))
df_csv.drop(columns=["texto_limpo"], errors="ignore").to_csv(caminho_csv, index=False, encoding="utf-8")

print(caminho_json)
print(caminho_csv)
print("\nTotal de artigos exportados:", len(df))