# -*- coding: utf-8 -*-
"""S004_Stopwords_Stemming_Lematizacao_POS_Framing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPXSvng_G76PDyhXjfdt_WKT3nDIh8hI

# Notebook 04 — Stopwords, Stemming/Lematização e POS Tagging

**Tema:** Como diferentes veículos de imprensa enquadram (*framing*) o conflito Israel-Palestina.

Este notebook parte do `corpus_tokenizado.json` (Notebook 03) e produz:

1. Remoção de stopwords e lematização com spaCy (`en_core_web_sm`);
2. Stemming (NLTK) só como comparação ilustrativa com a lematização como visto em aula, mas
   para a análise de framing usamos **lematização**, não stemming, porque preserva palavras reais e
   legíveis (melhor para relatar exemplos no trabalho);
3. POS tagging para extrair substantivos e, principalmente, **adjetivos** de cada artigo;
4. O cerne da análise: **quais adjetivos aparecem nas frases que mencionam Israel** vs. **quais
   adjetivos aparecem nas frases que mencionam Palestina/Gaza/Hamas**, por veículo

> **Limitação assumida:** quando uma frase menciona os dois lados ao mesmo tempo, ela é descartada
> dessa contagem específica (fica ambígua a quem o adjetivo se refere).

## 1. Instalando e importando as bibliotecas
"""

!pip install -q spacy nltk
!python -m spacy download en_core_web_sm -q

from pathlib import Path
from collections import Counter, defaultdict
import json

import pandas as pd
import spacy
import nltk
from nltk.stem import PorterStemmer

nltk.download("punkt", quiet=True)

nlp = spacy.load("en_core_web_sm")
stemmer = PorterStemmer()

print("spaCy carregado:", nlp.meta["name"], nlp.meta["version"])

"""## 2. Carregando o corpus tokenizado (saída do Notebook 03)

Se o caminho fixo não funcionar (aconteceu nos notebooks anteriores por causa da estrutura de pastas
no Drive), a célula procura o arquivo automaticamente.

"""

USE_DRIVE = True

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')

CAMINHO_ESPERADO = Path("/content/drive/MyDrive/Corpus/CorpusFramingIsraelPalestina_resultsnotebook2/CorpusFramingIsraelPalestina")

if USE_DRIVE and not (CAMINHO_ESPERADO / "metadados" / "corpus_tokenizado.json").exists():
    print("Caminho padrão não encontrado, procurando automaticamente no Drive...")
    encontrados = list(Path("/content/drive/MyDrive").rglob("corpus_tokenizado.json"))
    if encontrados:
        raiz = encontrados[0].parent.parent
        print("Encontrado em:", raiz)
    else:
        raise FileNotFoundError("corpus_tokenizado.json não encontrado em nenhum lugar do Drive.")
else:
    raiz = CAMINHO_ESPERADO if USE_DRIVE else Path("CorpusFramingIsraelPalestina_resultsnotebook2")

df = pd.read_json(raiz / "metadados" / "corpus_tokenizado.json")
print("Artigos carregados:", len(df))
print(df["grupo"].value_counts())
df.head(3)

"""## 3. Stopwords e lematização com spaCy

Processamos `texto_normalizado` (do Notebook 03) com spaCy de novo

"""

docs = list(nlp.pipe(df["texto_normalizado"].tolist(), batch_size=16))
df["doc"] = docs  # objetos spaCy Doc, usados no restante do notebook (não vai pro CSV/JSON final)

def tokens_sem_stopwords(doc):
    return [tok.lemma_.lower() for tok in doc if tok.is_alpha and not tok.is_stop]

df["lemas_sem_stopwords"] = df["doc"].apply(tokens_sem_stopwords)

print("Exemplo (primeiro artigo):")
print(df["lemas_sem_stopwords"].iloc[0][:20])

"""## 4. Lematização x Stemming (comparação ilustrativa)

Só para documentar a escolha metodológica no relatório: rodamos as duas técnicas sobre uma amostra
de palavras do corpus e comparamos. Reparem como o stemming corta a palavra até uma raiz que às
vezes nem é uma palavra real (`polici`, `israel`), enquanto a lematização devolve a forma de
dicionário

"""

amostra = list({tok for lista in df["lemas_sem_stopwords"] for tok in lista})[:15]

comparacao = pd.DataFrame({
    "token_lematizado": amostra,
    "stem_porter": [stemmer.stem(t) for t in amostra],
})
comparacao

"""## 5. POS tagging: substantivos e adjetivos por artigo

Extraímos separadamente os **substantivos** (`NOUN`/`PROPN`) e os **adjetivos** (`ADJ`) de cada
artigo, já lematizados e sem stopwords. Essas duas listas alimentam a frequência geral por veículo
no Notebook 05.

"""

def extrair_por_pos(doc, pos_desejado):
    return [
        tok.lemma_.lower()
        for tok in doc
        if tok.pos_ == pos_desejado and tok.is_alpha and not tok.is_stop
    ]

df["substantivos"] = df["doc"].apply(lambda d: extrair_por_pos(d, "NOUN") + extrair_por_pos(d, "PROPN"))
df["adjetivos"] = df["doc"].apply(lambda d: extrair_por_pos(d, "ADJ"))

df[["id", "veiculo", "substantivos", "adjetivos"]].head(3)

"""## 6. Adjetivos associados a cada lado do conflito

Para cada **frase** do artigo, verificamos se ela menciona termos do lado "Israel" e/ou do lado
"Palestina/Gaza/Hamas". Se a frase menciona só um dos lados, os adjetivos dessa frase são atribuídos
a esse lado. Frases que mencionam os dois lados ao mesmo tempo são descartadas dessa contagem
específica (ver limitação no topo do notebook).


"""

TERMOS_ISRAEL = {"israel", "israeli", "idf", "netanyahu"}
TERMOS_PALESTINA = {"palestine", "palestinian", "gaza", "hamas", "west bank"}


def classificar_frase(sent_text_lower):
    tem_israel = any(termo in sent_text_lower for termo in TERMOS_ISRAEL)
    tem_palestina = any(termo in sent_text_lower for termo in TERMOS_PALESTINA)
    if tem_israel and not tem_palestina:
        return "israel"
    if tem_palestina and not tem_israel:
        return "palestina"
    return None  # ambígua ou nenhuma menção, descartada


def adjetivos_por_lado(doc):
    resultado = {"israel": [], "palestina": []}
    for sent in doc.sents:
        lado = classificar_frase(sent.text.lower())
        if lado is None:
            continue
        adjetivos = [
            tok.lemma_.lower() for tok in sent
            if tok.pos_ == "ADJ" and tok.is_alpha and not tok.is_stop
        ]
        resultado[lado].extend(adjetivos)
    return resultado


df["adjetivos_por_lado"] = df["doc"].apply(adjetivos_por_lado)
df["adjetivos_israel"] = df["adjetivos_por_lado"].apply(lambda d: d["israel"])
df["adjetivos_palestina"] = df["adjetivos_por_lado"].apply(lambda d: d["palestina"])

df[["id", "veiculo", "adjetivos_israel", "adjetivos_palestina"]].head(5)

"""## 7. Comparação entre veículos: adjetivos mais frequentes por lado

Essa é a tabela mais importante do notebook para a análise de framing mostra, por veículo, quais
adjetivos aparecem mais perto de cada lado do conflito.

"""

TOP_N = 10

for veiculo in df["veiculo"].unique():
    subset = df[df["veiculo"] == veiculo]

    contagem_israel = Counter(tok for lista in subset["adjetivos_israel"] for tok in lista)
    contagem_palestina = Counter(tok for lista in subset["adjetivos_palestina"] for tok in lista)

    print(f"\n=== {veiculo} ===")
    print(f"Adjetivos perto de ISRAEL (top {TOP_N}):", contagem_israel.most_common(TOP_N))
    print(f"Adjetivos perto de PALESTINA/GAZA/HAMAS (top {TOP_N}):", contagem_palestina.most_common(TOP_N))

"""## 8. Frequência geral de substantivos e adjetivos por veículo

Complementa a seção anterior com uma visão mais ampla (não só frases sobre um lado específico)

"""

def top_por_veiculo(df, coluna, top_n=15):
    linhas = []
    for veiculo in df["veiculo"].unique():
        subset = df[df["veiculo"] == veiculo]
        contagem = Counter(tok for lista in subset[coluna] for tok in lista)
        for palavra, freq in contagem.most_common(top_n):
            linhas.append({"veiculo": veiculo, "palavra": palavra, "frequencia": freq})
    return pd.DataFrame(linhas)


df_top_substantivos = top_por_veiculo(df, "substantivos")
df_top_adjetivos = top_por_veiculo(df, "adjetivos")

print("Top substantivos por veículo:")
display(df_top_substantivos.head(20))

print("\nTop adjetivos por veículo:")
display(df_top_adjetivos.head(20))

"""## 9. Exportando para o Notebook 05



"""

(raiz / "resultados").mkdir(parents=True, exist_ok=True)

caminho_pos = raiz / "metadados" / "corpus_pos.json"
caminho_top_substantivos = raiz / "resultados" / "top_substantivos_por_veiculo.csv"
caminho_top_adjetivos = raiz / "resultados" / "top_adjetivos_por_veiculo.csv"

df_exportar = df.drop(columns=["doc", "adjetivos_por_lado"])
df_exportar.to_json(caminho_pos, orient="records", force_ascii=False, indent=2)

df_top_substantivos.to_csv(caminho_top_substantivos, index=False, encoding="utf-8")
df_top_adjetivos.to_csv(caminho_top_adjetivos, index=False, encoding="utf-8")

print(caminho_pos)
print(caminho_top_substantivos)
print(caminho_top_adjetivos)