# -*- coding: utf-8 -*-
"""S006_BagOfWords_Ngrams_Framing(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1JNwrPGrbwK13M7GZm6ybRzjQqt0wVI

# Notebook 06 — Bag of Words e N-grams: comparação quantitativa entre veículos

**Tema:** Como diferentes veículos de imprensa enquadram (*framing*) o conflito Israel-Palestina.

O Notebook 05 já trouxe uma comparação qualitativa (nuvens de palavras, adjetivos por lado,
bigramas contados manualmente). Este notebook complementa com a representação vetorial vista em
aula , que permite uma
pergunta mais quantitativa: **o quão parecido ou diferente é o vocabulário usado por cada veículo,
matematicamente?**

Etapas:

1. Agregar os textos de cada veículo num único "documento" (um veículo = um documento);
2. Construir a matriz documento-termo com `CountVectorizer` (unigramas e bigramas);
3. Calcular a **similaridade de cosseno** entre veículos, um número entre 0 e 1 que resume o
   quanto o vocabulário de dois veículos se sobrepõe;
4. Comparar esparsidade e tamanho do vocabulário conforme `n` aumenta (unigrama → trigrama);
5. Extrair os **bigramas mais distintivos de cada veículo** (os que mais diferenciam um do outro,
   não só os mais frequentes em geral).

## 1. Instalando e importando as bibliotecas
"""

!pip install -q scikit-learn plotly wordcloud

from pathlib import Path
from collections import Counter

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from wordcloud import WordCloud

print("Bibliotecas importadas.")

"""## 2. Carregando o corpus processado (saída do Notebook 04)

Usamos `lemas_sem_stopwords` (já lematizado, sem stopwords, do Notebook 04) como base, é a versão
de texto mais adequada para Bag of Words, pelos mesmos motivos vistos em aula:
reduzir ruído de palavras funcionais e variações morfológicas antes de vetorizar.

"""

USE_DRIVE = True

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')

CAMINHO_ESPERADO = Path("/content/drive/MyDrive/Corpus/CorpusFramingIsraelPalestina_resultsnotebook2/CorpusFramingIsraelPalestina")

if USE_DRIVE and not (CAMINHO_ESPERADO / "metadados" / "corpus_pos.json").exists():
    print("Caminho padrão não encontrado, procurando automaticamente no Drive...")
    encontrados = list(Path("/content/drive/MyDrive").rglob("corpus_pos.json"))
    if encontrados:
        raiz = encontrados[0].parent.parent
        print("Encontrado em:", raiz)
    else:
        raise FileNotFoundError("corpus_pos.json não encontrado em nenhum lugar do Drive.")
else:
    raiz = CAMINHO_ESPERADO if USE_DRIVE else Path("CorpusFramingIsraelPalestina_resultsnotebook2")

(raiz / "resultados").mkdir(parents=True, exist_ok=True)

df = pd.read_json(raiz / "metadados" / "corpus_pos.json")
print("Artigos carregados:", len(df))
print(df["veiculo"].value_counts())

"""## 3. Agregando um documento por veículo

Para comparar veículos (não artigos individuais), juntamos todos os `lemas_sem_stopwords` de cada
veículo numa única string

"""

documentos_por_veiculo = (
    df.groupby("veiculo")["lemas_sem_stopwords"]
    .apply(lambda listas: " ".join(tok for lista in listas for tok in lista))
)

veiculos = documentos_por_veiculo.index.tolist()
documentos = documentos_por_veiculo.tolist()

for veiculo, doc in zip(veiculos, documentos):
    print(f"{veiculo}: {len(doc.split())} tokens agregados")

"""## 4. Bag of Words (unigramas + bigramas) e matriz documento-termo"""

vectorizer = CountVectorizer(ngram_range=(1, 2), min_df=1)
X = vectorizer.fit_transform(documentos)
termos = vectorizer.get_feature_names_out()

print("Vocabulário (unigramas + bigramas):", len(termos), "termos")

df_bow = pd.DataFrame(X.toarray(), columns=termos, index=veiculos)
df_bow.iloc[:, :15]  # amostra das primeiras colunas, a matriz completa é grande

fig = px.imshow(
    X.toarray(),
    x=termos,
    y=veiculos,
    labels={"x": "Termo", "y": "Veículo", "color": "Contagem"},
    aspect="auto",
    title="Matriz documento-termo (amostra visual — pode ficar densa com muitos termos)",
)
fig.show()

"""## 5. Similaridade de cosseno entre veículos

Quanto mais perto de 1, mais parecido é o vocabulário (incluindo bigramas) usado pelos dois
veículos; quanto mais perto de 0, mais distinto.

"""

similaridade = cosine_similarity(X)

fig = px.imshow(
    similaridade,
    x=veiculos,
    y=veiculos,
    text_auto=".2f",
    zmin=0,
    zmax=1,
    color_continuous_scale="Blues",
    title="Similaridade de cosseno entre veículos (unigramas + bigramas)",
)
fig.show()

df_similaridade = pd.DataFrame(similaridade, index=veiculos, columns=veiculos)
df_similaridade.to_csv(raiz / "resultados" / "similaridade_cosseno_veiculos.csv", encoding="utf-8")
df_similaridade

"""## 6. Vocabulário e esparsidade conforme `n` aumenta

Reproduzindo a análise do S009 (seção 11): quanto maior o `n`, mais features (mais específicas),
porém mais esparsidade (cada termo aparece em poucos documentos)

"""

comparacao = []

for n in [1, 2, 3]:
    cv = CountVectorizer(ngram_range=(n, n))
    Xn = cv.fit_transform(documentos)
    total = Xn.shape[0] * Xn.shape[1]
    esparsidade = 100 * (1 - Xn.nnz / total) if total > 0 else 0
    comparacao.append({"n": n, "features": Xn.shape[1], "esparsidade_pct": round(esparsidade, 1)})

df_comparacao = pd.DataFrame(comparacao)
print(df_comparacao)

fig, eixos = plt.subplots(1, 2, figsize=(11, 4))
eixos[0].plot(df_comparacao["n"], df_comparacao["features"], marker="o")
eixos[0].set_title("Nº de features x tamanho do n-gram")
eixos[0].set_xlabel("n")
eixos[1].plot(df_comparacao["n"], df_comparacao["esparsidade_pct"], marker="o", color="darkorange")
eixos[1].set_title("Esparsidade (%) x tamanho do n-gram")
eixos[1].set_xlabel("n")
plt.tight_layout()
plt.show()

"""## 7. Bigramas mais distintivos de cada veículo

Bigramas mais frequentes em geral tendem a ser genéricos. Para achar o que **diferencia** um
veículo do outro, comparamos a frequência relativa de cada bigrama entre os dois: um bigrama é
"distintivo de X" quando aparece proporcionalmente muito mais em X do que nos outros veículos.

"""

cv_bigramas = CountVectorizer(ngram_range=(2, 2))
Xb = cv_bigramas.fit_transform(documentos)
termos_bigramas = cv_bigramas.get_feature_names_out()

df_bigramas = pd.DataFrame(Xb.toarray(), columns=termos_bigramas, index=veiculos)
df_freq_relativa = df_bigramas.div(df_bigramas.sum(axis=1), axis=0)  # normaliza por tamanho do documento

TOP_N = 12

for veiculo in veiculos:
    outros = [v for v in veiculos if v != veiculo]
    diferenca = df_freq_relativa.loc[veiculo] - df_freq_relativa.loc[outros].mean()
    top_distintivos = diferenca.sort_values(ascending=False).head(TOP_N)

    print(f"\n=== Bigramas mais distintivos de {veiculo} ===")
    for bigrama, score in top_distintivos.items():
        if score > 0:
            print(f"  {bigrama}  (score={score:.4f})")

"""## 8. Nuvem de bigramas por veículo

Complementa as nuvens de palavras do Notebook 05 (que eram de palavras isoladas) com nuvens de
**bigramas**, que mostram expressões recorrentes em vez de termos soltos.

"""

fig, eixos = plt.subplots(1, len(veiculos), figsize=(7 * len(veiculos), 6))
if len(veiculos) == 1:
    eixos = [eixos]

for ax, veiculo in zip(eixos, veiculos):
    freq_bigramas = Counter()
    for bigrama, contagem in zip(termos_bigramas, df_bigramas.loc[veiculo]):
        if contagem > 0:
            freq_bigramas[bigrama] = contagem

    if freq_bigramas:
        wc = WordCloud(width=700, height=500, background_color="white", collocations=False)
        wc.generate_from_frequencies(freq_bigramas)
        ax.imshow(wc, interpolation="bilinear")
    ax.set_title(f"{veiculo} — bigramas")
    ax.axis("off")

plt.tight_layout()
plt.savefig(raiz / "resultados" / "nuvens_bigramas_por_veiculo.png", dpi=150, bbox_inches="tight")
plt.show()

"""## 9. Salvando os resultados"""

caminho_bow = raiz / "resultados" / "bag_of_words_por_veiculo.csv"
caminho_comparacao_n = raiz / "resultados" / "comparacao_tamanho_ngram.csv"

df_bow.to_csv(caminho_bow, encoding="utf-8")
df_comparacao.to_csv(caminho_comparacao_n, index=False, encoding="utf-8")

print(caminho_bow)
print(caminho_comparacao_n)
print(raiz / "resultados" / "similaridade_cosseno_veiculos.csv")
print(raiz / "resultados" / "nuvens_bigramas_por_veiculo.png")